name: Build and Deploy React App

on:
  push:
    branches:
      - main  # ajuste esta linha para corresponder à sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # ajuste esta linha para a versão Node.js que você está usando

    - name: Instalar dependências
      run: npm ci

    - name: Construir aplicativo React
      run: npm run build

    - name: Implantação no GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./build
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
    - name: Deploy with gh-pages
      run: |
            git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
            npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
